name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: factureo_backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (ruff)
        working-directory: factureo_backend
        run: |
          ruff version
          ruff check .

      - name: Run tests (pytest)
        working-directory: factureo_backend
        env:
          # Usa una URI dummy que no intente conectar (solo importa módulos)
          MONGO_URI: mongodb://localhost:27017/factureo
          SECRET_KEY: test-secret
        run: |
          pytest -q
